### ISSUE TITLE
vite:dep-scan error: Failed to resolve entry for package "vite-ssr"

### ISSUE THREAD

**Issue by AlessioGr** [frandiox/vite-ssr#142]
When trying to run my project, I'm getting the following error:
```
> @ dev C:\Development\GitHub\Hangar\frontend-new
> vite-ssr dev --port 3333

X [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/.pnpm/vite@2.8.3/node_modules/vite/dist/node/chunks/dep-f9d9421a.js:29521:10:
      29521 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:29521:11)
    at resolvePackageEntry (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:29517:9)
    at tryNodeResolve (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:29333:20)
    at Context.resolveId (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:29150:28)
    at Object.resolveId (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:38255:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:38458:26)
    at async C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:38596:34
    at async callback (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:920:28)
    at async handleRequest (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:700:30)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/vite@2.8.3/node_modules/vite/dist/node/chunks/dep-f9d9421a.js:38586:18:
      38586 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:38586:19)
    at handlePlugins (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:842:23)
    at Object.buildOrServe (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:1136:7)
    at C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:2064:17
    at new Promise (<anonymous>)
    at Object.build (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:2063:14)
    at Object.build (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:1913:51)
    at C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:38416:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    src/main.ts:3:36:
      3 │ import viteSSR, { ClientOnly } from "vite-ssr";
        ╵                                     ~~~~~~~~~~

C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:1602
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/.pnpm/vite@2.8.3/node_modules/vite/dist/node/chunks/dep-f9d9421a.js:29521:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:1602:15)
    at C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:1248:28
    at runOnEndCallbacks (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:1033:63)
    at buildResponseToResult (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:1246:7)
    at C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:1355:14
    at C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:665:9
    at handleIncomingPacket (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:762:9)
    at Socket.readFromStdout (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:632:7)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: Error: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.
          at packageEntryFailure (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:29521:11)
          at resolvePackageEntry (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:29517:9)
          at tryNodeResolve (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:29333:20)
          at Context.resolveId (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:29150:28)
          at Object.resolveId (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:38255:55)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async resolve (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:38458:26)
          at async C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\vite@2.8.3\node_modules\vite\dist\node\chunks\dep-f9d9421a.js:38596:34
          at async callback (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:920:28)
          at async handleRequest (C:\Development\GitHub\Hangar\frontend-new\node_modules\.pnpm\esbuild@0.14.22\node_modules\esbuild\lib\main.js:700:30),
      location: {
        column: 10,
        file: 'node_modules/.pnpm/vite@2.8.3/node_modules/vite/dist/node/chunks/dep-f9d9421a.js',
        length: 0,
        line: 29521,
        lineText: '    throw new Error(`Failed to resolve entry for package "${id}". ` +\n' +
          '    at packageEntryFailure (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\vite@2.8.3\\node_modules\\vite\\dist\\node\\chunks\\dep-f9d9421a.js:29521:11)\n' +
          '    at resolvePackageEntry (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\vite@2.8.3\\node_modules\\vite\\dist\\node\\chunks\\dep-f9d9421a.js:29517:9)\n' +
          '    at tryNodeResolve (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\vite@2.8.3\\node_modules\\vite\\dist\\node\\chunks\\dep-f9d9421a.js:29333:20)\n' +
          '    at Context.resolveId (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\vite@2.8.3\\node_modules\\vite\\dist\\node\\chunks\\dep-f9d9421a.js:29150:28)\n' +
          '    at Object.resolveId (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\vite@2.8.3\\node_modules\\vite\\dist\\node\\chunks\\dep-f9d9421a.js:38255:55)\n' +
          '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
          '    at async resolve (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\vite@2.8.3\\node_modules\\vite\\dist\\node\\chunks\\dep-f9d9421a.js:38458:26)\n' +
          '    at async C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\vite@2.8.3\\node_modules\\vite\\dist\\node\\chunks\\dep-f9d9421a.js:38596:34\n' +
          '    at async callback (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\esbuild@0.14.22\\node_modules\\esbuild\\lib\\main.js:920:28)\n' +
          '    at async handleRequest (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\esbuild@0.14.22\\node_modules\\esbuild\\lib\\main.js:700:30)',
        namespace: 'file',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 18,
            file: 'node_modules/.pnpm/vite@2.8.3/node_modules/vite/dist/node/chunks/dep-f9d9421a.js',
            length: 9,
            line: 38586,
            lineText: '            build.onResolve({\n' +
              '    at setup (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\vite@2.8.3\\node_modules\\vite\\dist\\node\\chunks\\dep-f9d9421a.js:38586:19)\n' +
              '    at handlePlugins (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\esbuild@0.14.22\\node_modules\\esbuild\\lib\\main.js:842:23)\n' +
              '    at Object.buildOrServe (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\esbuild@0.14.22\\node_modules\\esbuild\\lib\\main.js:1136:7)\n' +
              '    at C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\esbuild@0.14.22\\node_modules\\esbuild\\lib\\main.js:2064:17\n' +
              '    at new Promise (<anonymous>)\n' +
              '    at Object.build (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\esbuild@0.14.22\\node_modules\\esbuild\\lib\\main.js:2063:14)\n' +
              '    at Object.build (C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\esbuild@0.14.22\\node_modules\\esbuild\\lib\\main.js:1913:51)\n' +
              '    at C:\\Development\\GitHub\\Hangar\\frontend-new\\node_modules\\.pnpm\\vite@2.8.3\\node_modules\\vite\\dist\\node\\chunks\\dep-f9d9421a.js:38416:54\n' +
              '    at Array.map (<anonymous>)',
            namespace: 'file',
            suggestion: ''
          },
          text: 'This error came from the "onResolve" callback registered here:'
        },
        {
          location: {
            column: 36,
            file: 'src/main.ts',
            length: 10,
            line: 3,
            lineText: 'import viteSSR, { ClientOnly } from "vite-ssr";',
            namespace: '',
            suggestion: ''
          },
          text: 'The plugin "vite:dep-scan" was triggered by this import'
        }
      ],
      pluginName: 'vite:dep-scan',
      text: 'Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.'
    }
  ],
  warnings: []
}
 ELIFECYCLE  Command failed with exit code 1.
```

Is there any compatibility issue with vite-ssr and vite:dep-scan?

**Comment by frandiox** [comment]
Please downgrade to Vite 2.7.x -- https://github.com/frandiox/vite-ssr/issues/141#issuecomment-1041391817

**Comment by AlessioGr** [comment]
Aah I see that worked, thank you for your response!
