### ISSUE TITLE
Incompatible with Vite 2.8

### ISSUE THREAD

**Issue by mkilpatrick** [frandiox/vite-ssr#144]
`✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10:
      29537 │     throw new Error(`Failed to resolve entry for package "${i...
            ╵           ^

    at packageEntryFailure (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:11)
    at resolvePackageEntry (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:29533:9)
    at tryNodeResolve (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:29349:20)
    at Context.resolveId (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:29166:28)
    at Object.resolveId (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:38271:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async resolve (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:38474:26)
    at async /Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:38612:34
    at async callback (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:923:28)
    at async handleRequest (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:703:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:18:
      38602 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:19)
    at handlePlugins (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:845:23)
    at Object.buildOrServe (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:1139:7)
    at /Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:2080:17
    at new Promise (<anonymous>)
    at Object.build (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:2079:14)
    at Object.build (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:1929:51)
    at /Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:38432:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    src/main.jsx:3:20:
      3 │ import viteSSR from 'vite-ssr'
        ╵                     ~~~~~~~~~~

✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10:
      29537 │     throw new Error(`Failed to resolve entry for package "${i...
            ╵           ^

    at packageEntryFailure (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:11)
    at resolvePackageEntry (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:29533:9)
    at tryNodeResolve (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:29349:20)
    at Context.resolveId (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:29166:28)
    at Object.resolveId (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:38271:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async resolve (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:38474:26)
    at async /Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:38612:34
    at async callback (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:923:28)
    at async handleRequest (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:703:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:18:
      38602 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (/Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:19)
    at handlePlugins (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:845:23)
    at Object.buildOrServe (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:1139:7)
    at /Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:2080:17
    at new Promise (<anonymous>)
    at Object.build (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:2079:14)
    at Object.build (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:1929:51)
    at /Users/mkilpatrick/Desktop/vite/node_modules/vite/dist/node/chunks/dep-9c153816.js:38432:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    src/App.jsx:5:27:
      5 │ import { ClientOnly } from 'vite-ssr'
        ╵                            ~~~~~~~~~~

(node:81876) UnhandledPromiseRejectionWarning: Error: Build failed with 2 errors:
node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.
node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vite-ssr". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:1605:15)
    at /Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:1251:28
    at runOnEndCallbacks (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:1036:63)
    at buildResponseToResult (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:1249:7)
    at /Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:1358:14
    at /Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:668:9
    at handleIncomingPacket (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:765:9)
    at Socket.readFromStdout (/Users/mkilpatrick/Desktop/vite/node_modules/esbuild/lib/main.js:635:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:81876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:81876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by salqueng** [comment]
I have created a workaround - https://github.com/frandiox/vite-ssr/discussions/143#discussioncomment-2294141

**Comment by MarkLyck** [comment]
@frandiox any update on this? Maybe implement @salqueng's workaround into the main package?

**Comment by frandiox** [comment]
@MarkLyck @salqueng Can you have a look at #153 ? That uses virtual modules instead of aliases, which should be more robust.
