### ISSUE TITLE
manualChunks  errors in version 0.17.1

### ISSUE THREAD

**Issue by gitsheny** [frandiox/vite-ssr#191]
> vite-ssr\examples\vue\vite.config.js
```
build: {
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes('node_modules')) {
            return id.toString().split('node_modules/')[1].split('/')[0].toString()
          }
        },
      },
    },
  },
```
build and serve, it errors. but success in version 0.16.0
```
$ node ../node-server/index vue
D:\Projects\vite-ssr\examples\vue\dist\server\assets\@vue-224e90fb.js:14580
const { createComponentInstance, setCurrentRenderingInstance, setupComponent, renderComponentRoot, normalizeVNode } = vue.vueExports.ssrUtils;
                                                                                                                                     ^        

TypeError: Cannot read property 'ssrUtils' of undefined
    at Object.<anonymous> (D:\JetBrains\Projects\1\vite-ssr\examples\vue\dist\server\assets\@vue-224e90fb.js:14580:134)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (D:\JetBrains\Projects\1\vite-ssr\examples\vue\dist\server\assets\vue-41d7bc3f.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

```

**Comment by gitsheny** [comment]
when i use pnpm install, its ok 
when i use npm i, its error
emm...
```
  "dependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "@vue/compiler-sfc": "^3.2.26",
    "@vue/server-renderer": "^3.2.26",
    "@vueuse/head": "^0.6.0",
    "vite": "4.1.x",
    "vue": "^3.2.26",
    "vue-router": "^4.0.12",
    "vite-ssr": "0.17.1",
    "express": "4.18.2",
    "express-static-gzip": "2.1.7"
  }
```
