### ISSUE TITLE
Cannot read property 'ssrUtils' of undefined

### ISSUE THREAD

**Issue by gitsheny** [frandiox/vite-ssr#192]
if i set manualChunks with vite version > 4.0.4.
build and serve, its error.
if vite version 4.0.4 its ok
maybe its vite problem ?

```
 // vite.config.js
  build: {
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes('node_modules')) {
            return id.toString().split('node_modules/')[1].split('/')[0].toString()
          }
        },
      },
    },
  },
```

```
D:\test\v2\dist\server\assets\@vue-7c2e52dd.js:14903
const { createComponentInstance, setCurrentRenderingInstance, setupComponent, renderComponentRoot, normalizeVNode } = vue.vueExports.ssrUtils;
                                                                                                                                     ^        

TypeError: Cannot read property 'ssrUtils' of undefined
    at Object.<anonymous> (D:\test\v2\dist\server\assets\@vue-7c2e52dd.js:14903:134)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (D:\test\v2\dist\server\assets\vue-66bf41ba.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

**Comment by gitsheny** [comment]
https://github.com/vitejs/vite/blob/e57cacfb412c7cac9f5e793357df445990d7535f/packages/vite/src/node/plugins/resolve.ts#L1047
