### ISSUE TITLE
import { createSSRApp } from 'vue' *(Cannot use import statement outside a module)

### ISSUE THREAD

**Issue by zernonia** [frandiox/vite-ssr#21]
After I run `vite-ssr build`,  then I follow the example for deploying to Serverless function (Vercel) but i ran into such problem.

There's no error during build phases. 

Below are the error while previewing Vercel locally.
```
C:\Coding\my-vitesse-app\serverless\node_modules\vite-ssr\vue\entry-server.js:1
import { createSSRApp } from 'vue';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\sians\AppData\Roaming\npm\node_modules\vercel\node_modules\ts-node\src\index.ts:832:44)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module.<anonymous> (C:\Coding\my-vitesse-app\serverless\api\renderer\main.js:21:15)     
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
Error! `node api/index.js` failed with exit code 1
```

Then I tried to deploy straight to vercel, similar error as such

```
undefined	ERROR	/var/task/node_modules/vite-ssr/vue/entry-server.js:1
import { createSSRApp } from 'vue';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module.<anonymous> (/var/task/api/renderer/main.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
RequestId: 0cf21fd7-254a-4550-97c3-c6bc3948db7d Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Finally, I've tried deploy as ExpressJS, similar issue happens.

**Comment by frandiox** [comment]
@zernonia This path seems wrong: `C:\Coding\my-vitesse-app\serverless\node_modules\vite-ssr\vue\entry-server.js`

`vite-ssr` shouldn't be in `my-vitesse-app/serverless/node_modules`, but in `my-vitesse-app/node_modules` 🤔 

Have you modified `vite.config.ts` or `serverless/package.json`?

Can you verify that your `dist/server/main.js` (after building) contains something like this around lines 30-40?

```js
var NProgress = require("nprogress");
var vue = require("vue");
var serverRenderer = require("@vue/server-renderer");
var vueRouter = require("vue-router");
var head = require("@vueuse/head");
var vueI18n = require("vue-i18n");
var core = require("@vueuse/core");
```

Also, make sure you use Node 14.x and run `npm install` in `serverless` folder.

**Comment by zernonia** [comment]
Hi @frandiox , thanks for the reply. I've checked my `dist/server/main.js` and it shows that I have the following lines

```javascript
var NProgress = require("nprogress");
var viteSSR = require("vite-ssr/vue/entry-server");   // extra line compare to yours
var head = require("@vueuse/head");
var vue = require("vue");
var serverRenderer = require("@vue/server-renderer");
var vueRouter = require("vue-router");
var vueI18n = require("vue-i18n");
var core = require("@vueuse/core");
```

I deleted the previous template and clone it again, then run the build step and it seems to have solved the problem.
I've tried to reproduce the similar issue again but failed to do so

Thank you so much for awesome ssr solution and sorry for the trouble..
